---
abstract: 'Implementation of various techniques used in data compression.'
author:
  - 'Daniel Șuteu <trizen@cpan.org>'
build_requires:
  Test::More: '0'
configure_requires:
  Module::Build: '0'
dynamic_config: 0
generated_by: 'Module::Build version 0.4234, CPAN::Meta::Converter version 2.150010'
license: artistic_2
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Compression-Util
provides:
  Compression::Util:
    file: lib/Compression/Util.pm
    version: '0.04'
requires:
  Exporter: '0'
  List::Util: '1.45'
  Test::More: '0'
  perl: v5.36.0
resources:
  bugtracker: https://github.com/trizen/Compression-Util/issues
  homepage: https://github.com/trizen/Compression-Util
  license: http://www.perlfoundation.org/artistic_license_2_0
  repository: https://github.com/trizen/Compression-Util
version: '0.04'
x_serialization_backend: 'CPAN::Meta::YAML version 0.018'
